import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../../styles/Home.module.css';
import Greetings from '../components/Greetings/Greetings';
import Events from '../components/Events/Events';
import Feed from '../components/Feed/Feed';
import Visitors from '../components/Visitors/Visitors';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import { useTranslation, withTranslation } from 'next-i18next';
import { useRouter } from 'next/router';

const Home: NextPage = () => {
  const { locale, push, locales } = useRouter();

  const { t } = useTranslation('common');

  const handleClick = (l: any) => {
    push('/', undefined, { locale: l });
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/frontend/public/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <p>{t('description')}</p>
        <h1>{locale}</h1>
        <div className={styles.navbar}>
          {locales &&
            locales.map((l, i) => {
              return (
                <button key={l} onClick={() => handleClick(l)}>
                  {l}
                </button>
              );
            })}
        </div>
        <p style={{ fontSize: '1.5rem' }}>{t('title')}</p>
        <br />
        <p style={{ fontSize: '1.5rem' }}>{t('greeting')}</p>
        <Greetings />
        <Events />
        <Feed />
        <Visitors />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

Home.getInitialProps = async () => ({
  namespacesRequired: ['common']
});

export default withTranslation('common')(Home);

export async function getStaticProps({ locale }: { locale: any }) {
  return {
    props: {
      ...(await serverSideTranslations(locale, ['common']))
    }
  };
}
